M48
; DRILL file {KiCad 7.0.7} date Sun Oct 15 16:54:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-15T16:54:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X16.9998Y-5.1565
X17.2274Y-5.1565
T2
X13.6672Y-4.7343
X13.6672Y-5.0492
T0
M30
